# Lab 1a. Arrays
Probability and Statistics, Spring 2017    
CC BY-NC-SA, Sakari Lukkarinen   
Helsinki Metropolia University of Applied Sciences

Book: Johansson. (2015). [Numerical Python: A Practical Techniques Approach For Industry.](https://metropolia.finna.fi/Record/nelli15.3710000000486209)

## Chapter 2. Vectors, Matrices and Multidimensional Arrays

Import numerical python library and refer it as np.

In [10]:
import numpy as np

Create a numerical array having the values: `1, 3, 3, 4, 2, 2, 5, 6, 9'

In [52]:
import numpy as np
x = np.array([1, 3, 3, 4, 2, 2, 5, 6, 7])
print(x)

[1 3 3 4 2 2 5 6 7]


Find the dimensions, shape, size, data type and number of bytes in the array.

In [20]:
print(x.shape)
print(len(x))
print(x.ndim)
print(x.size)
print(x.dtype)
print(x.dtype.name)


(9,)
9
1
9
int32
int32


Create an array of of shape (100,1) filled with 

a) zeros,    
b) ones,    
c) value of 3.14.   

In [24]:
import numpy as np
a = np.zeros((100,1))
b = np.ones((100,1))
c = np.full((100,1),3.14)
print(a)
print(b)
print(c)

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.

Create an array having numbers from 1 to 100.

In [69]:
d = np.zeros((100,))
for i in range (1,101):  
    d[i-1] = i
    
print(d)

[   1.    2.    3.    4.    5.    6.    7.    8.    9.   10.   11.   12.
   13.   14.   15.   16.   17.   18.   19.   20.   21.   22.   23.   24.
   25.   26.   27.   28.   29.   30.   31.   32.   33.   34.   35.   36.
   37.   38.   39.   40.   41.   42.   43.   44.   45.   46.   47.   48.
   49.   50.   51.   52.   53.   54.   55.   56.   57.   58.   59.   60.
   61.   62.   63.   64.   65.   66.   67.   68.   69.   70.   71.   72.
   73.   74.   75.   76.   77.   78.   79.   80.   81.   82.   83.   84.
   85.   86.   87.   88.   89.   90.   91.   92.   93.   94.   95.   96.
   97.   98.   99.  100.]


Create an array having number from 1.0 to 3.0 with step size of 0.1

In [74]:
e = np.arange(1,3.1,0.1) 
print(e)

[ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4
  2.5  2.6  2.7  2.8  2.9  3. ]


Create an array having 10 evenly spaced value between 1.0 and 7.2.

In [78]:
f = np.linspace(1,7.2,10) 
print(f)

[ 1.          1.68888889  2.37777778  3.06666667  3.75555556  4.44444444
  5.13333333  5.82222222  6.51111111  7.2       ]


What is the value of the 5th element in the array created in previous exercise?

In [80]:
f[4]

3.7555555555555555

Select the elements from 5 to 7 from the array.

In [104]:
f[(f>5)][f[(f>5)]<7]


array([ 5.13333333,  5.82222222,  6.51111111])

Select two last elements from the array.

In [108]:
f[8:10]

array([ 6.51111111,  7.2       ])

Create a 10 x 10 array filled with zeros.

In [109]:
g = np.zeros((10,10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

Replace the values with values from 1 to 100 in the previous array.

In [136]:
g = np.zeros((10,10))
j=0
k=0
for i in range (1,101):    
    g[j,k] = i
    k=k+1
    if(i%2 == 0 and i%5 == 0 ):
        j=j+1
        k=0
print(g)

[[   1.    2.    3.    4.    5.    6.    7.    8.    9.   10.]
 [  11.   12.   13.   14.   15.   16.   17.   18.   19.   20.]
 [  21.   22.   23.   24.   25.   26.   27.   28.   29.   30.]
 [  31.   32.   33.   34.   35.   36.   37.   38.   39.   40.]
 [  41.   42.   43.   44.   45.   46.   47.   48.   49.   50.]
 [  51.   52.   53.   54.   55.   56.   57.   58.   59.   60.]
 [  61.   62.   63.   64.   65.   66.   67.   68.   69.   70.]
 [  71.   72.   73.   74.   75.   76.   77.   78.   79.   80.]
 [  81.   82.   83.   84.   85.   86.   87.   88.   89.   90.]
 [  91.   92.   93.   94.   95.   96.   97.   98.   99.  100.]]


Clear (change the values to zero) the 3rd row in the array.

In [144]:
g = np.zeros((10,10))
j=0
k=0
for i in range (1,101):    
    g[j,k] = i
    k=k+1
    if(i%2 == 0 and i%5 == 0 ):
        j=j+1
        k=0

g[2:3]=0
print(g)

[[   1.    2.    3.    4.    5.    6.    7.    8.    9.   10.]
 [  11.   12.   13.   14.   15.   16.   17.   18.   19.   20.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [  31.   32.   33.   34.   35.   36.   37.   38.   39.   40.]
 [  41.   42.   43.   44.   45.   46.   47.   48.   49.   50.]
 [  51.   52.   53.   54.   55.   56.   57.   58.   59.   60.]
 [  61.   62.   63.   64.   65.   66.   67.   68.   69.   70.]
 [  71.   72.   73.   74.   75.   76.   77.   78.   79.   80.]
 [  81.   82.   83.   84.   85.   86.   87.   88.   89.   90.]
 [  91.   92.   93.   94.   95.   96.   97.   98.   99.  100.]]


Clear the 7th column in the array

In [146]:
g = np.zeros((10,10))
j=0
k=0
for i in range (1,101):    
    g[j,k] = i
    k=k+1
    if(i%2 == 0 and i%5 == 0 ):
        j=j+1
        k=0

g[2:3]=0
g[6:7]=0
print(g)

[[   1.    2.    3.    4.    5.    6.    7.    8.    9.   10.]
 [  11.   12.   13.   14.   15.   16.   17.   18.   19.   20.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [  31.   32.   33.   34.   35.   36.   37.   38.   39.   40.]
 [  41.   42.   43.   44.   45.   46.   47.   48.   49.   50.]
 [  51.   52.   53.   54.   55.   56.   57.   58.   59.   60.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [  71.   72.   73.   74.   75.   76.   77.   78.   79.   80.]
 [  81.   82.   83.   84.   85.   86.   87.   88.   89.   90.]
 [  91.   92.   93.   94.   95.   96.   97.   98.   99.  100.]]


Create and array having the values `1, 3, 3, 5, 4, 2, 7, 9`

In [148]:
h=np.array([1,3,3,5,4,2,7,9])
print(h)

[1 3 3 5 4 2 7 9]


Find all values in the array being greater than 4.

In [149]:
h[h>4]

array([5, 7, 9])

Change all the value being less or equal to 3 to value `nan`

In [164]:
h=np.array([1,3,3,5,4,2,7,9] , dtype = float)
h[h<4]=np.nan
print(h)

8
[ nan  nan  nan   5.   4.  nan   7.   9.]


Create two arrays, the first having values `1, 3, 5` and the second `2, 4, 6`

In [170]:
k = np.array([1,3,5], dtype = float)
l = np.array([2,4,6], dtype = float)
print(k)
print(l)

[ 1.  3.  5.]
[ 2.  4.  6.]


Combine the arrays horizontally (e.g. make a one long row).

In [176]:
m = np.concatenate((k,l), axis = 0)
print(m)

[ 1.  3.  5.  2.  4.  6.]


Combine the arrays vertically (e.g. make an array having two rows).

In [178]:
n = np.vstack((k,l))
print(n)

[[ 1.  3.  5.]
 [ 2.  4.  6.]]


Combine the arrays and sort them in ascending order.

In [180]:
m = np.append(k,l)
m.sort(axis=0)
print(m)

[ 1.  2.  3.  4.  5.  6.]


Create an array having numbers from 0.0 to 1.0 with stepsize 0.05.

In [182]:
o = np.arange(0,1.1,0.1) 
print(o)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


Calculate the sine of each element in the previous exercise.

In [183]:
p = np.sin(o)
print(p)

[ 0.          0.09983342  0.19866933  0.29552021  0.38941834  0.47942554
  0.56464247  0.64421769  0.71735609  0.78332691  0.84147098]


Calculate the square root of each element.

In [184]:
q = np.sqrt(o)
print(q)

[ 0.          0.31622777  0.4472136   0.54772256  0.63245553  0.70710678
  0.77459667  0.83666003  0.89442719  0.9486833   1.        ]


Calculate $y=3x^2 - 5x + 3$, when x varies from -5 to 5 with stepsize of 0.5

In [203]:
r = np.arange(-5,5.1,0.5)
koko = r.size
s = r.copy()
for i in range (0, koko):
    val = r[i];
    result = 3*(val**2) - 5*val + 3
    s[i] = result
print(s)

[ 103.     86.25   71.     57.25   45.     34.25   25.     17.25   11.
    6.25    3.      1.25    1.      2.25    5.      9.25   15.     22.25
   31.     41.25   53.  ]


Convert the values of the previous exercise to the closest integer.

In [204]:
t = s.astype(int)
print(t)

[103  86  71  57  45  34  25  17  11   6   3   1   1   2   5   9  15  22
  31  41  53]


Create a numerical array having the values: `1, 3, 3, 4, 2, 2, 5, 6, 9'

In [205]:
u=np.array([1,3,3,4,2,2,5,6,9])
print(u)

[1 3 3 4 2 2 5 6 9]


Calculate the mean and standard deviation of the array

In [208]:
mean = u.mean()
std = np.std(u)
print(mean)
print(std)

3.88888888889
2.33068632927


Find the minimum, the maximum, and the median values of the array.

In [213]:
mini = u.min()
maxi = u.max(axis=0)
medi = np.median(u)
print(mini)
print(maxi)
print(medi)

1
9
3.0


Find the index for the minimum value.

In [266]:
ukoko = u.size
for i in range (0, ukoko):
    if(u[i] == u.min()):
        print(i)

np.argmin(u)


0


0

Find the index for the maximum value.

In [219]:
ukoko = u.size
for i in range (0, ukoko):
    if(u[i] == u.max(axis=0)):
        print(i)

8


Sum all elements together.

In [220]:
total = u.sum()
print(total)

35


Check if all elements are less than 9.

In [261]:
ukoko = u.size
count = 0
for i in range (0, ukoko):
    if(u[i]>=9):
        count = count + 1
print("There are", count, "numbers larger or equal 9")

all(u<9)

There are 1 numbers larger or equal 9


False

Check if any of the elements is equal to 5

In [267]:
ukoko = u.size
count = 0
for i in range (0, ukoko):
    if(u[i] == 5):
        count = count + 1
print("There are", count, "numbers equal 5")

any(u==5)

There are 1 numbers equal 5


True

Sort the values in array in descending order (from maximum to minimum).

In [251]:
u=np.array([1,3,3,4,2,2,5,6,9])
u.sort(axis=0)
u[::-1]
print(u)

[1 2 2 3 3 4 5 6 9]


Multiply the following matrices using the matrix multiplication (dot-product).   
$ A= \begin{bmatrix}
1 & 2 \\
5 & 3\\
\end{bmatrix}$ and 
$x = \begin{bmatrix}
-2 \\ 
3\\ 
\end{bmatrix}$

In [252]:
A = np.array([(1,2), (5,3)], dtype = float)
x = np.array([-2, 3], dtype = float)
v = A.dot(x)
print(v)

[ 4. -1.]


Import from `numpy.linalg` module the functions `inv` and `solve`

In [253]:
from numpy.linalg import inv, solve

Find the inverse of matrix A.

In [255]:
A = np.array([(1,2), (5,3)], dtype = float)
inv(A)

array([[-0.42857143,  0.28571429],
       [ 0.71428571, -0.14285714]])

Using `solve` function solve the system of equations 
$\begin{bmatrix}1 & 2 \\ 5 & 3\end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = \begin{bmatrix} 9 \\ 31 \end{bmatrix}$

In [258]:
A = np.array([(1,2), (5,3)], dtype = float)
b = np.array([9, 31], dtype = float)
x = np.linalg.solve(A, b)
print(x)

#np.allclose(np.dot(A, x), b)

[ 5.  2.]


True

Solve the $Ax=b$, where $A = \begin{bmatrix} 4 & 8 & 20 \\ 8 & 13 & 16 \\ 20 & 16 & -91\end{bmatrix}$ and $b = \begin{bmatrix}24 \\ 18 \\ -199 \end{bmatrix}$.

In [260]:
A = np.array([(4,8,20), (8,13,16), (20, 16, -91)], dtype = float)
b = np.array([24, 18, -199], dtype = float)
x = np.linalg.solve(A, b)
print(x)

#np.allclose(np.dot(A, x), b)

[-883.  642.  -79.]


True